### PR TITLE
non-mutating munge_data

### PR DESCRIPTION
**Pull request by d-netto**

### CODE REVIEW

**Comment by andreasnoack** [comment]
We used to have a version like that but the result can't be inferred so it's too costly.

**Comment by ChrisRackauckas** [comment]
It needs to be done since Zygote cannot infer through the constructor with this mutation. Maybe the easiest fix for now would be to create new dispatches so that Missing does what it currently does and a non-missing dispatch that just does the no-mutating thing but fast. That will make everything with Zygote work well while not impacting Pumas speeds.

**Comment by andreasnoack** [comment]
It’s fine to rewrite these methods such that they work with Zygote. We just shouldn’t use DataFrames for it because of the inference issue.

**Comment by d-netto** [comment]
I believe the latest commit should be a possible solution without using dataframes

**Comment by d-netto** [comment]
Ok, it's passing.

**Pull request merged**
