### PR TITLE
Implement series recipes for interpolations

### PR DESCRIPTION
**Pull request by asinghvi17**
With this PR, you should be able to do:
```julia
@series
    seriestype := :loess # any *_interp or *_spline also
    x := xs
    y := ys
end
```
and have it "just work", generating a smoothed series.

### CODE REVIEW

**Comment by asinghvi17** [comment]
Test failures on MacOS seem unrelated.

**Comment by asinghvi17** [comment]
Still WIP - need to fix the quadratic interpolation, and individually test.

**Comment by asinghvi17** [comment]
ps

**Comment by ChrisRackauckas** [comment]
Looks like it's just floating point issues. Would you mind submitting a PR to relax the tolerances a bit before we tag?

**Pull request merged**
